version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: /opt/codedeploy-agent/deployment-root/d49dc135-e0d6-4d5e-8517-33912fd56fc2/d-K4BUUVNUZ/deployment-archive/scripts/installapache.sh
      runas: root
    - location: /opt/codedeploy-agent/deployment-root/d49dc135-e0d6-4d5e-8517-33912fd56fc2/d-K4BUUVNUZ/deployment-archive/scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: /opt/codedeploy-agent/deployment-root/d49dc135-e0d6-4d5e-8517-33912fd56fc2/d-K4BUUVNUZ/deployment-archive/scripts/restartapache.sh
      runas: root
